### ISSUE TITLE
update or remove the shortcuts to the artifacts.

### ISSUE THREAD

**Issue by costateixeira** [hl7-be/patientwill#9]
Just noting that the artifacts menu still has a link to profiles, extensions and valuesets.
These links are not correct, not sure why they are there. Best to have a link to the artifact index.

**Comment by bdc-ehealth** [comment]
WG: this is still a temporary version of the IG. Of course we will clean this up.

**Comment by AlexisVZ-MDS** [comment]
I have a strong preference to have an up-to-date IG, meaning very quickly updated / aligned with what's defined in the Business Rules and/or has been discussed during the meetings. Because this forces us to think in Fhir semantics & practices and avoids confusion when both are not aligned. 

Or couldn't we even - as soon as an IG is online - strive to document everything directly and clearly in this IG (incl. profile, valuesets, extensions and artifacts)  and not needing an updated "business rules document" anymore ?
